packages:
  - packages/*
  - configs/*
overrides:
  # overrides dependencies from catalog:template to use local packages instead of deployed ones
  "@svebcomponents/build": workspace:*
  "@svebcomponents/auto-options": workspace:*
  "@svebcomponents/ssr": workspace:*
catalog:
  "@lit-labs/ssr": 3.3.1
  "@lit-labs/ssr-dom-shim": 1.3.0
  "@rollup/plugin-node-resolve": 16.0.1
  "@rollup/plugin-typescript": 12.1.2
  "@rollup/plugin-virtual": 3.0.2
  "@sveltejs/package": 2.3.10
  "@types/node": 22.14.1
  "@types/estree": "1.0.7"
  esm-env: 1.2.2
  magic-string: 0.30.17
  publint: 0.3.11
  rollup: 4.40.0
  rollup-plugin-svelte: 7.2.2
  svelte: 5.28.2
  svelte-check: 4.1.6
  turbo: 2.5.2
  tslib: 2.8.1
  vite: 6.2.6
  vitest: 3.1.1
  zimmerframe: 1.1.2
  "@changesets/cli": 2.29.3
  # configs/typescript-config
  typescript: 5.8.3
  "@tsconfig/strictest": 2.0.5
  "@tsconfig/svelte": 5.0.4
  # configs/prettier-config
  prettier: 3.5.3
  prettier-plugin-svelte: 3.3.3
  # configs/eslint-config
  eslint: 9.30.1
  "@eslint/js": 9.30.1
  eslint-config-prettier: 10.1.2
  eslint-plugin-svelte: 3.5.1
  globals: 16.0.0
  typescript-eslint: 8.29.1
