packages:
  - packages/*
  - configs/*
  - e2e/*

catalog:
  '@changesets/cli': 2.29.3
  '@eslint/js': 9.30.1
  '@lit-labs/ssr': 3.3.1
  '@lit-labs/ssr-dom-shim': 1.3.0
  '@sveltejs/package': 2.3.10
  '@sveltejs/vite-plugin-svelte': 6.1.0
  '@tsconfig/strictest': 2.0.5
  '@tsconfig/svelte': 5.0.4
  '@types/estree': 1.0.7
  '@types/node': 22.14.1
  '@vitest/browser': 3.2.4
  eslint: 9.30.1
  eslint-config-prettier: 10.1.2
  eslint-plugin-svelte: 3.5.1
  esm-env: 1.2.2
  globals: 16.0.0
  magic-string: 0.30.17
  playwright: 1.45.0
  prettier: 3.5.3
  prettier-plugin-svelte: 3.3.3
  publint: 0.3.12
  rolldown: 1.0.0-beta.29
  rollup-plugin-svelte: 7.2.2
  svelte: 5.28.2
  svelte-check: 4.1.6
  tslib: 2.8.1
  turbo: 2.5.2
  typescript: 5.8.3
  typescript-eslint: 8.29.1
  vite: 7.0.6
  vitest: 3.2.4
  zimmerframe: 1.1.2

catalogMode: strict
