packages:
  - apps/*
  - packages/*
  - components/*
  - configs/*
catalog:
  "@chromatic-com/storybook": 3.2.6
  "@lit-labs/ssr": 3.3.1
  "@lit-labs/ssr-dom-shim": 1.3.0
  "@open-wc/lit-helpers": 0.7.0
  "@playwright/test": 1.51.1
  "@rollup/plugin-node-resolve": 16.0.1
  "@rollup/plugin-typescript": 12.1.2
  "@rollup/plugin-virtual": 3.0.2
  "@storybook/addon-essentials": 8.6.12
  "@storybook/blocks": 8.6.12
  "@storybook/test": 8.6.12
  "@storybook/web-components": 8.6.12
  "@storybook/web-components-vite": 8.6.12
  "@sveltejs/adapter-auto": 6.0.0
  "@sveltejs/kit": 2.20.5
  "@sveltejs/package": 2.3.10
  "@sveltejs/vite-plugin-svelte": 5.0.3
  "@tsconfig/strictest": 2.0.5
  "@tsconfig/svelte": 5.0.4
  "@types/node": 22.14.1
  "@types/estree": "1.0.7"
  eslint: 9.24.0
  "@eslint/js": 9.24.0
  eslint-config-prettier: 10.1.2
  eslint-plugin-svelte: 3.5.1
  esm-env: 1.2.2
  globals: 16.0.0
  lit: 3.3.0
  magic-string: 0.30.17
  prettier: 3.5.3
  prettier-plugin-svelte: 3.3.3
  publint: 0.3.11
  rollup: 4.40.0
  rollup-plugin-svelte: 7.2.2
  storybook: 8.6.12
  svelte: 5.28.2
  svelte-check: 4.1.6
  turbo: 2.5.2
  typescript: 5.8.3
  tslib: 2.8.1
  typescript-eslint: 8.32.0
  vite: 6.2.6
  vitest: 3.1.1
  zimmerframe: 1.1.2
  "@changesets/cli": 2.29.3
