import { test, expect, assert, vi } from "vitest";
import { createSSRApp } from "vue";

import { svebcomponents } from "@svebcomponents/ssr-vue";

// generated by test/hydrationFixture.globalSetup.ts from real Vue SSR output
import ssrFixture from "./generated/hydration-fixture.html?raw";

import SyncApp from "../../src/SyncApp.vue";

const nextMacrotask = () => new Promise((resolve) => setTimeout(resolve, 0));

test("Vue hydrates around a server-rendered custom element without re-creating it", async () => {
  // setHTMLUnsafe is required for declarative shadow DOM to attach when
  // setting HTML programmatically
  document.body.setHTMLUnsafe(`<div id="host">${ssrFixture}</div>`);
  const host = document.querySelector("#host");
  assert(host);

  const component = document.querySelector("sync-component");
  assert(component);
  const ssrShadowRoot = component.shadowRoot;
  assert(
    ssrShadowRoot,
    "Vue's SSR output must parse into a declarative shadow root",
  );

  // brand the server-rendered nodes so we can prove they survive both the
  // custom element's own hydration and Vue's
  const ssrH1 = ssrShadowRoot.querySelector("h1");
  assert(ssrH1);
  expect(ssrH1.textContent).toBe("Hydration Test");
  ssrH1.setAttribute("data-ssr-node", "kept");

  const ssrLightDom = host.querySelector("#light-dom");
  assert(ssrLightDom, "light-dom children must survive outside the shadow root");
  ssrLightDom.setAttribute("data-ssr-node", "kept");

  // upgrade: define the custom element only now, like a real page loading its
  // client bundle after HTML parsing
  await import("@svebcomponents/e2e.ssr/sync");
  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  // now hydrate the Vue app around it
  const warn = vi.spyOn(console, "warn").mockImplementation(() => undefined);
  const error = vi.spyOn(console, "error").mockImplementation(() => undefined);

  const app = createSSRApp(SyncApp, { title: "Hydration Test" });
  app.use(svebcomponents());
  app.mount(host);
  await nextMacrotask();

  // Vue reports hydration mismatches as dev warnings and then patches over
  // them; nothing else in this test would fail if the wrapper's two branches
  // drifted apart, so the warnings are the assertion.
  const hydrationComplaints = [...warn.mock.calls, ...error.mock.calls]
    .map(([message]) => String(message))
    .filter((message) => message.includes("Hydration"));
  warn.mockRestore();
  error.mockRestore();

  expect(hydrationComplaints).toEqual([]);

  // the custom element instance itself was claimed, not replaced
  expect(document.querySelector("sync-component")).toBe(component);
  // same shadow root instance — never cleared and re-attached
  expect(component.shadowRoot).toBe(ssrShadowRoot);

  // the server-rendered shadow nodes were adopted, not replaced
  const h1 = component.shadowRoot?.querySelector("h1");
  expect(h1).toBe(ssrH1);
  expect(h1?.getAttribute("data-ssr-node")).toBe("kept");

  // and so were the light-dom children Vue owns
  expect(host.querySelector("#light-dom")).toBe(ssrLightDom);
  expect(host.querySelector("#light-dom")?.getAttribute("data-ssr-node")).toBe(
    "kept",
  );

  // the rich prop round-tripped through the serialized-props channel
  expect(component.shadowRoot?.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  expect(
    component.shadowRoot?.querySelector("script[data-svebcomponents-ssr-props]"),
  ).toBeNull();
});

test("the hydrated element stays reactive to attribute updates", async () => {
  document.body.setHTMLUnsafe(`<div id="host">${ssrFixture}</div>`);
  const host = document.querySelector("#host");
  assert(host);

  await import("@svebcomponents/e2e.ssr/sync");
  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  const app = createSSRApp(SyncApp, { title: "Hydration Test" });
  app.use(svebcomponents());
  app.mount(host);
  await nextMacrotask();

  const component = document.querySelector("sync-component");
  assert(component);
  const ssrH1 = component.shadowRoot?.querySelector("h1");

  component.setAttribute("count", "7");
  await nextMacrotask();

  expect(component.shadowRoot?.querySelector("#count")?.textContent).toBe(
    "Count: number-7",
  );
  // the update reused the hydrated DOM rather than re-rendering from scratch
  expect(component.shadowRoot?.querySelector("h1")).toBe(ssrH1);
});
