import { test, expect, assert } from "vitest";

// generated by test/hydrationFixture.globalSetup.ts from real Astro output
import ssrFixture from "./generated/hydration-fixture.html?raw";

const nextMacrotask = () => new Promise((resolve) => setTimeout(resolve, 0));

/**
 * Astro ships no client-side JavaScript for these elements, so unlike the Vue
 * and React suites there is no host framework to hydrate and no client wrapper
 * to keep in step. The element is on its own: the parser attaches the
 * declarative shadow root, the client bundle upgrades the element, and it
 * hydrates its own shadow content.
 *
 * That makes this the simplest of the three client stories, and these tests
 * exist to keep it that way — if Astro ever started emitting markup that
 * interfered, this would catch it.
 */
const setupPage = async () => {
  // setHTMLUnsafe is required for declarative shadow DOM to attach when
  // setting HTML programmatically
  document.body.setHTMLUnsafe(`<div id="host">${ssrFixture}</div>`);
  const host = document.querySelector("#host");
  assert(host);

  await import("@svebcomponents/e2e.ssr/sync");
  await customElements.whenDefined("sync-component");
  // svelte custom elements wait a microtask before initializing
  await nextMacrotask();
  await nextMacrotask();

  return host;
};

test("the element hydrates its server-rendered shadow root in place", async () => {
  document.body.setHTMLUnsafe(`<div id="host">${ssrFixture}</div>`);
  const component = document.querySelector("sync-component");
  assert(component);

  const ssrShadowRoot = component.shadowRoot;
  assert(ssrShadowRoot, "Astro's output must parse into a declarative shadow root");
  const ssrH1 = ssrShadowRoot.querySelector("h1");
  assert(ssrH1);
  expect(ssrH1.textContent).toBe("Hydration Test");
  ssrH1.setAttribute("data-ssr-node", "kept");

  await import("@svebcomponents/e2e.ssr/sync");
  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  // same shadow root instance — never cleared and re-attached
  expect(component.shadowRoot).toBe(ssrShadowRoot);
  // the server-rendered node was adopted, not replaced
  expect(component.shadowRoot?.querySelector("h1")).toBe(ssrH1);
  expect(ssrH1.getAttribute("data-ssr-node")).toBe("kept");
});

test("the shadow template leaves no stray node in the light DOM", async () => {
  const host = await setupPage();

  expect(host.querySelector("template")).toBeNull();
  const component = document.querySelector("sync-component");
  expect(component?.firstElementChild?.tagName).toBe("P");
});

test("rich props round-trip through the serialized-props channel", async () => {
  await setupPage();
  const component = document.querySelector("sync-component");
  assert(component);

  expect(component.shadowRoot?.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  expect(
    component.shadowRoot?.querySelector("script[data-svebcomponents-ssr-props]"),
  ).toBeNull();
});

test("the hydrated element stays reactive to attribute updates", async () => {
  await setupPage();
  const component = document.querySelector("sync-component");
  assert(component);
  const ssrH1 = component.shadowRoot?.querySelector("h1");

  component.setAttribute("count", "7");
  await nextMacrotask();

  expect(component.shadowRoot?.querySelector("#count")?.textContent).toBe(
    "Count: number-7",
  );
  expect(component.shadowRoot?.querySelector("h1")).toBe(ssrH1);
});
