import { test, expect, assert } from "vitest";

// generated by test/hydrationFixture.globalSetup.ts from the real SSR output
import ssrFixture from "./generated/hydration-fixture.html?raw";

const nextMacrotask = () =>
  new Promise((resolve) => setTimeout(resolve, 0));

test("hydrates server-rendered declarative shadow DOM, reusing its nodes", async () => {
  // parse the SSR output — setHTMLUnsafe is required for declarative shadow
  // DOM to attach when setting HTML programmatically
  document.body.setHTMLUnsafe(ssrFixture);

  const component = document.querySelector("sync-component");
  assert(component);
  const ssrShadowRoot = component.shadowRoot;
  assert(ssrShadowRoot, "declarative shadow root must be attached pre-upgrade");

  // brand the server-rendered nodes so we can prove they survive hydration
  const ssrH1 = ssrShadowRoot.querySelector("h1");
  assert(ssrH1);
  expect(ssrH1.textContent).toBe("Hydration Test");
  ssrH1.setAttribute("data-ssr-node", "kept");
  const ssrStyle = ssrShadowRoot.querySelector("style");
  assert(ssrStyle, "SSR output must carry the component styles");

  // upgrade: define the custom element only now, like a real page loading its
  // client bundle after HTML parsing
  await import("../../dist/client/sync.js");
  await customElements.whenDefined("sync-component");
  // svelte custom elements wait a microtask before initializing
  await nextMacrotask();
  await nextMacrotask();

  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);
  // same shadow root instance — not cleared and re-attached
  expect(shadowRoot).toBe(ssrShadowRoot);

  // the server-rendered node was adopted, not replaced
  const h1 = shadowRoot.querySelector("h1");
  assert(h1);
  expect(h1).toBe(ssrH1);
  expect(h1.getAttribute("data-ssr-node")).toBe("kept");
  expect(h1.textContent).toBe("Hydration Test");

  // styles were adopted, not duplicated (svelte dedupes by style id)
  expect(shadowRoot.querySelectorAll("style")).toHaveLength(1);

  // the rich prop (no attribute representation) round-tripped through the
  // serialized-props channel — without it, hydration would have mismatched
  expect(shadowRoot.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  // and the transport script element was consumed
  expect(
    shadowRoot.querySelector("script[data-svebcomponents-ssr-props]"),
  ).toBeNull();

  // and the hydrated component is fully reactive
  component.setAttribute("count", "7");
  await nextMacrotask();
  const count = shadowRoot.querySelector("#count");
  assert(count);
  expect(count.textContent).toBe("Count: number-7");
  // the update reused the hydrated DOM as well
  expect(shadowRoot.querySelector("h1")).toBe(ssrH1);
});

test("falls back to a fresh mount when there is no server-rendered content", async () => {
  document.body.innerHTML = `<sync-component title="Mounted" count="1"></sync-component>`;

  await import("../../dist/client/sync.js");
  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  const component = document.querySelector("sync-component");
  assert(component);
  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);
  const h1 = shadowRoot.querySelector("h1");
  assert(h1);
  expect(h1.textContent).toBe("Mounted");
});
