import { test, expect, assert } from "vitest";

// generated by test/hydrationFixture.globalSetup.ts from the real SSR output
import ssrFixture from "./generated/hydration-fixture.html?raw";

const nextMacrotask = () =>
  new Promise((resolve) => setTimeout(resolve, 0));

test("hydrates server-rendered declarative shadow DOM, reusing its nodes", async () => {
  // parse the SSR output — setHTMLUnsafe is required for declarative shadow
  // DOM to attach when setting HTML programmatically
  document.body.setHTMLUnsafe(ssrFixture);

  const component = document.querySelector("sync-component");
  assert(component);
  const ssrShadowRoot = component.shadowRoot;
  assert(ssrShadowRoot, "declarative shadow root must be attached pre-upgrade");

  // brand the server-rendered nodes so we can prove they survive hydration
  const ssrH1 = ssrShadowRoot.querySelector("h1");
  assert(ssrH1);
  expect(ssrH1.textContent).toBe("Hydration Test");
  ssrH1.setAttribute("data-ssr-node", "kept");
  const ssrStyle = ssrShadowRoot.querySelector("style");
  assert(ssrStyle, "SSR output must carry the component styles");

  // upgrade: define the custom element only now, like a real page loading its
  // client bundle after HTML parsing
  await import("../../dist/client/sync.js");
  await customElements.whenDefined("sync-component");
  // svelte custom elements wait a microtask before initializing
  await nextMacrotask();
  await nextMacrotask();

  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);
  // same shadow root instance — not cleared and re-attached
  expect(shadowRoot).toBe(ssrShadowRoot);

  // the server-rendered node was adopted, not replaced
  const h1 = shadowRoot.querySelector("h1");
  assert(h1);
  expect(h1).toBe(ssrH1);
  expect(h1.getAttribute("data-ssr-node")).toBe("kept");
  expect(h1.textContent).toBe("Hydration Test");

  // styles were adopted, not duplicated (svelte dedupes by style id)
  expect(shadowRoot.querySelectorAll("style")).toHaveLength(1);

  // the rich prop (no attribute representation) round-tripped through the
  // serialized-props channel — without it, hydration would have mismatched
  expect(shadowRoot.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  // and the transport script element was consumed
  expect(
    shadowRoot.querySelector("script[data-svebcomponents-ssr-props]"),
  ).toBeNull();

  // and the hydrated component is fully reactive
  component.setAttribute("count", "7");
  await nextMacrotask();
  const count = shadowRoot.querySelector("#count");
  assert(count);
  expect(count.textContent).toBe("Count: number-7");
  // the update reused the hydrated DOM as well
  expect(shadowRoot.querySelector("h1")).toBe(ssrH1);

  // $host() must resolve to the upgraded custom element in the hydrated
  // path: the event dispatched via $host() fires on <sync-component> itself
  const events: Event[] = [];
  component.addEventListener("sync-emitted", (event) => events.push(event));
  (shadowRoot.querySelector("#emit") as HTMLButtonElement).click();
  expect(events).toHaveLength(1);
  expect((events[0] as CustomEvent).detail).toBe("from-host");
  expect(events[0]?.target).toBe(component);
});

test("falls back to a fresh mount when there is no server-rendered content", async () => {
  document.body.innerHTML = `<sync-component title="Mounted" count="1"></sync-component>`;

  await import("../../dist/client/sync.js");
  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  const component = document.querySelector("sync-component");
  assert(component);
  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);
  const h1 = shadowRoot.querySelector("h1");
  assert(h1);
  expect(h1.textContent).toBe("Mounted");

  // $host() works in svelte's own fresh-mount path too (parity check)
  const events: Event[] = [];
  component.addEventListener("sync-emitted", (event) => events.push(event));
  (shadowRoot.querySelector("#emit") as HTMLButtonElement).click();
  expect(events).toHaveLength(1);
  expect(events[0]?.target).toBe(component);
});

/**
 * Builds a variant of the SSR fixture with attacker-style markup injected
 * inside the declarative shadow root, before the genuine transport script.
 */
const poisonedFixture = (injectedShadowMarkup: string) => {
  const marker = '<template shadowrootmode="open">';
  assert(ssrFixture.includes(marker), "fixture must contain a shadow root");
  return ssrFixture.replace(marker, `${marker}${injectedShadowMarkup}`);
};

test("ignores forged transport scripts planted before the server payload", async () => {
  // simulate markup that reached the shadow root ahead of the real payload
  // (e.g. via {@html ...} content): an earlier transport script must not be
  // able to override server-serialized props on upgrade
  const forgedScript =
    '<script type="application/json" data-svebcomponents-ssr-props>' +
    '{"meta":{"note":"forged note"}}</script>';
  document.body.setHTMLUnsafe(poisonedFixture(forgedScript));

  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  const component = document.querySelector("sync-component");
  assert(component);
  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);

  // the genuine (last) payload won: the rich prop round-tripped, the forged
  // one was discarded without ever being parsed
  expect(shadowRoot.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  // every transport script was consumed — including the forged one, so no
  // stale payloads linger in the DOM
  expect(
    shadowRoot.querySelectorAll("script[data-svebcomponents-ssr-props]"),
  ).toHaveLength(0);
});

test("hydrates despite an unparseable typed attribute", async () => {
  // a malformed Object/Array attribute must not abort hydration via an
  // unhandled rejection: the prop is skipped, everything else hydrates
  const broken = ssrFixture.replace(
    "<sync-component",
    '<sync-component meta="not-json{"',
  );
  assert(broken !== ssrFixture);
  document.body.setHTMLUnsafe(broken);

  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  const component = document.querySelector("sync-component");
  assert(component);
  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);

  // hydration completed: the malformed attribute was skipped, the serialized
  // meta rich prop still came through, and the element stays reactive
  expect(shadowRoot.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  component.setAttribute("count", "9");
  await nextMacrotask();
  expect(shadowRoot.querySelector("#count")?.textContent).toBe(
    "Count: number-9",
  );
});

test("survives an unparseable typed attribute written after hydration", async () => {
  // the same malformed value, now arriving through a live attribute write.
  // svelte's generated attributeChangedCallback JSON.parses Object/Array
  // attributes unguarded, so this would otherwise throw out of a custom
  // element reaction and surface as an unhandled page error
  document.body.setHTMLUnsafe(ssrFixture);

  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  const component = document.querySelector("sync-component");
  assert(component);
  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);

  // a throw from a custom element reaction never reaches setAttribute's
  // caller — the browser reports it to the global error handler instead, so
  // that is where the regression shows up
  const reportedErrors: unknown[] = [];
  const captureError = (event: ErrorEvent) => {
    reportedErrors.push(event.error);
    event.preventDefault();
  };
  window.addEventListener("error", captureError);
  try {
    component.setAttribute("meta", "not-json{");
    await nextMacrotask();
  } finally {
    window.removeEventListener("error", captureError);
  }
  expect(reportedErrors).toEqual([]);

  // the bad write was ignored rather than applied, and the element stays
  // reactive to well-formed ones
  expect(shadowRoot.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  component.setAttribute("meta", '{"note":"replaced"}');
  await nextMacrotask();
  expect(shadowRoot.querySelector("#note")?.textContent).toBe("replaced");
});

test("lets a non-conversion error from an attribute write propagate", async () => {
  // the guard above must stay narrow: only svelte's JSON conversion is
  // swallowed, so a genuine failure still reaches the page
  document.body.setHTMLUnsafe(ssrFixture);

  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  const component = document.querySelector("sync-component");
  assert(component);

  // called directly rather than via setAttribute: the browser reports a throw
  // from a custom element *reaction* to the global error handler instead of
  // propagating it to the caller, which would hide the distinction under test
  const element = component as unknown as {
    attributeChangedCallback: (
      name: string,
      oldValue: string | null,
      newValue: string | null,
    ) => void;
    $$c: { $set: (props: Record<string, unknown>) => void };
  };

  // an Object-typed prop with an unparseable value: swallowed
  expect(() => {
    element.attributeChangedCallback("meta", null, "not-json{");
  }).not.toThrow();

  // `count` is a Number prop — its conversion cannot throw, so an error raised
  // while applying it is a real one and must keep propagating
  const failure = new Error("component update failed");
  const originalSet = element.$$c.$set;
  element.$$c.$set = () => {
    throw failure;
  };
  try {
    expect(() => {
      element.attributeChangedCallback("count", null, "5");
    }).toThrow(failure);
  } finally {
    element.$$c.$set = originalSet;
  }
});

test("adopts a declarative template the parser could not attach", async () => {
  // The element is defined *first* here, which inverts the ordering the test
  // above relies on. The parser only honours `<template shadowrootmode>` while
  // the host has no shadow root, so once the definition has loaded the element
  // upgrades on its start tag, svelte's constructor calls `attachShadow`, and
  // the template that follows is refused and left in the light DOM.
  //
  // That is not an edge case: it is what all markup arriving after the initial
  // document looks like. React streams the contents of a Suspense boundary in
  // late, and any client-side navigation builds its markup from script — by
  // then the component bundle has long since run. `innerHTML` reproduces the
  // same ordering here without needing a framework, because it never attaches
  // a declarative shadow root either.
  await import("../../dist/client/sync.js");
  await customElements.whenDefined("sync-component");

  const host = document.createElement("div");
  document.body.replaceChildren(host);
  host.innerHTML = ssrFixture;

  // Establishes the browser behaviour this test turns on, so a future change
  // in it cannot leave the test quietly passing for the wrong reason: parsing
  // the same markup on an *undefined* tag leaves the template untouched, which
  // is why any shadow root on the element below has to have come from the
  // adoption path rather than from the parser.
  const control = document.createElement("div");
  control.innerHTML =
    '<undefined-control-element><template shadowrootmode="open">x</template></undefined-control-element>';
  const controlHost = control.firstElementChild;
  assert(controlHost);
  expect(controlHost.shadowRoot).toBeNull();
  expect(controlHost.querySelector("template[shadowrootmode]")).not.toBeNull();

  const component = host.querySelector("sync-component");
  assert(component);

  await nextMacrotask();
  await nextMacrotask();

  const shadowRoot = component.shadowRoot;
  assert(shadowRoot);

  // the server's markup was adopted rather than thrown away and re-rendered
  expect(shadowRoot.querySelector("h1")?.textContent).toBe("Hydration Test");
  // the rich prop only exists in the serialized-props payload inside that
  // template, so a client-side re-render could not have produced it
  expect(shadowRoot.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );

  // and the template is gone from the light DOM. A host framework rendered no
  // such child, so leaving it behind is a hydration mismatch for React and a
  // stray node for everyone else.
  expect(component.querySelector("template")).toBeNull();
});
