import { test, expect, assert } from "vitest";
import { hydrate, unmount } from "svelte";

import ClientHost from "./ClientHost.svelte";
// generated by test/clientHostFixture.globalSetup.ts, by server-rendering the
// very same host component through the server wrapper
import hostFixture from "./generated/host-fixture.html?raw";

// The other half of the story: the wrapper on the *hydration* path. A svelte
// host hydrating over server-rendered markup must claim the existing custom
// element rather than re-create it — the guarantee Client.svelte's structural
// parity with Server.svelte exists to protect — while still delivering the
// camelCase props the spread would have mangled.

const nextMacrotask = () => new Promise((resolve) => setTimeout(resolve, 0));

test("hydrates over a server-rendered host without re-creating the element", async () => {
  const target = document.createElement("div");
  document.body.append(target);
  // setHTMLUnsafe: declarative shadow roots only attach when parsed this way
  target.setHTMLUnsafe(hostFixture);

  const ssrElement = target.querySelector("sync-component");
  assert(ssrElement, "fixture must contain the server-rendered element");
  const ssrShadowRoot = ssrElement.shadowRoot;
  assert(ssrShadowRoot, "declarative shadow root must attach pre-upgrade");

  // the server render already delivered the camelCase props
  expect(ssrShadowRoot.querySelector("#label")?.textContent).toBe(
    "Label shown",
  );
  // brand the server-rendered nodes so we can prove they survive
  ssrElement.setAttribute("data-ssr-element", "kept");
  const ssrLabel = ssrShadowRoot.querySelector("#label");
  assert(ssrLabel);
  ssrLabel.setAttribute("data-ssr-node", "kept");

  const instance = hydrate(ClientHost, {
    target,
    props: {
      title: "Hydrated Host",
      count: 3,
      showLabel: true,
      richDetail: { note: "rich prop survived hydration" },
    },
  });

  await customElements.whenDefined("sync-component");
  await nextMacrotask();
  await nextMacrotask();

  // the host claimed the server-rendered element instead of replacing it
  const component = target.querySelector("sync-component");
  expect(component).toBe(ssrElement);
  expect(component?.getAttribute("data-ssr-element")).toBe("kept");

  // ...and the element claimed its own server-rendered shadow content
  const shadowRoot = component?.shadowRoot;
  expect(shadowRoot).toBe(ssrShadowRoot);
  expect(shadowRoot?.querySelector("#label")).toBe(ssrLabel);
  expect(shadowRoot?.querySelector("#label")?.getAttribute("data-ssr-node")).toBe(
    "kept",
  );

  // both camelCase props are live on the hydrated element
  expect(
    (component as unknown as { showLabel: boolean; richDetail: unknown })
      .showLabel,
  ).toBe(true);
  expect(
    (component as unknown as { richDetail: { note: string } }).richDetail,
  ).toEqual({ note: "rich prop survived hydration" });
  expect(shadowRoot?.querySelector("#detail")?.textContent).toBe(
    "rich prop survived hydration",
  );

  void unmount(instance);
  target.remove();
});
