import { test, expect, assert, vi } from "vitest";
import { hydrateRoot } from "react-dom/client";

// generated by test/hydrationFixture.globalSetup.tsx from real React SSR output
import ssrFixture from "./generated/hydration-fixture.html?raw";

import SyncApp from "../../src/SyncApp.js";

const nextMacrotask = () => new Promise((resolve) => setTimeout(resolve, 0));

/**
 * React 19 hydrates concurrently, so a single macrotask is not enough to know
 * it has committed. Touching the DOM before then makes React compare its tree
 * against markup that has since changed, which reports as a hydration
 * mismatch that has nothing to do with the server output.
 */
const settleHydration = async () => {
  for (let i = 0; i < 5; i++) await nextMacrotask();
};

/**
 * Parses the SSR fixture and upgrades the custom element, mirroring a real
 * page: HTML is parsed first (which is what makes the declarative shadow root
 * attach), the client bundle defines the element, and only then does React
 * hydrate.
 */
const setupPage = async () => {
  // setHTMLUnsafe is required for declarative shadow DOM to attach when
  // setting HTML programmatically
  document.body.setHTMLUnsafe(`<div id="host">${ssrFixture}</div>`);
  const host = document.querySelector("#host");
  assert(host);

  await import("@svebcomponents/e2e.ssr/sync");
  await customElements.whenDefined("sync-component");
  // svelte custom elements wait a microtask before initializing
  await nextMacrotask();
  await nextMacrotask();

  return host;
};

test("React hydrates around a server-rendered custom element without re-creating it", async () => {
  const host = await setupPage();

  const component = document.querySelector("sync-component");
  assert(component);
  const ssrShadowRoot = component.shadowRoot;
  assert(
    ssrShadowRoot,
    "React's SSR output must parse into a declarative shadow root",
  );

  // brand the server-rendered nodes so we can prove they survive both the
  // custom element's own hydration and React's
  const ssrH1 = ssrShadowRoot.querySelector("h1");
  assert(ssrH1);
  expect(ssrH1.textContent).toBe("Hydration Test");
  ssrH1.setAttribute("data-ssr-node", "kept");

  // The light-dom child is React's to hydrate, so it is identified by node
  // identity rather than branded with an attribute: React compares attributes
  // it did not render against its own tree and would report the brand itself
  // as a hydration mismatch.
  const ssrLightDom = host.querySelector("#light-dom");
  assert(ssrLightDom, "light-dom children must survive outside the shadow root");

  // React reports hydration mismatches through onRecoverableError and dev
  // warnings, then re-renders the subtree client-side. Nothing else here
  // would fail if that happened, so the diagnostics are the assertion.
  const recoverableErrors: string[] = [];
  const consoleError = vi
    .spyOn(console, "error")
    .mockImplementation(() => undefined);

  const root = hydrateRoot(host, <SyncApp title="Hydration Test" />, {
    onRecoverableError: (error) => {
      recoverableErrors.push(String(error));
    },
  });
  await settleHydration();

  const consoleComplaints = consoleError.mock.calls
    .map((args) => args.map((arg) => String(arg)).join(" "))
    .filter(
      (message) =>
        message.includes("hydrat") ||
        message.includes("Hydration") ||
        message.includes("did not match"),
    );
  consoleError.mockRestore();

  expect(recoverableErrors).toEqual([]);
  expect(consoleComplaints).toEqual([]);

  // the custom element instance itself was claimed, not replaced
  expect(document.querySelector("sync-component")).toBe(component);
  // same shadow root instance — never cleared and re-attached
  expect(component.shadowRoot).toBe(ssrShadowRoot);

  // the server-rendered shadow nodes were adopted, not replaced
  const h1 = component.shadowRoot?.querySelector("h1");
  expect(h1).toBe(ssrH1);
  expect(h1?.getAttribute("data-ssr-node")).toBe("kept");

  // and so was the light-dom child React owns
  expect(host.querySelector("#light-dom")).toBe(ssrLightDom);

  // the rich prop round-tripped through the serialized-props channel
  expect(component.shadowRoot?.querySelector("#note")?.textContent).toBe(
    "rich prop survived",
  );
  expect(
    component.shadowRoot?.querySelector("script[data-svebcomponents-ssr-props]"),
  ).toBeNull();

  root.unmount();
});

test("the shadow template leaves no stray node in the light DOM", async () => {
  const host = await setupPage();

  // the parser must have consumed the <template shadowrootmode> into the
  // shadow root; a leftover template would mean React's client tree and the
  // DOM disagree about the element's first child
  expect(host.querySelector("template")).toBeNull();
  expect(
    document.querySelector("sync-component")?.firstElementChild?.tagName,
  ).toBe("P");
});

test("the hydrated element stays reactive to attribute updates", async () => {
  const host = await setupPage();

  const root = hydrateRoot(host, <SyncApp title="Hydration Test" />);
  await settleHydration();

  const component = document.querySelector("sync-component");
  assert(component);
  const ssrH1 = component.shadowRoot?.querySelector("h1");

  component.setAttribute("count", "7");
  await nextMacrotask();

  expect(component.shadowRoot?.querySelector("#count")?.textContent).toBe(
    "Count: number-7",
  );
  // the update reused the hydrated DOM rather than re-rendering from scratch
  expect(component.shadowRoot?.querySelector("h1")).toBe(ssrH1);

  root.unmount();
});
