name: Publish

on:
  push:
    branches:
      - main
    paths:
      - "packages/*/package.json"
      - "packages/*/CHANGELOG.md"
      - "configs/*/package.json"
      - "configs/*/CHANGELOG.md"

permissions:
  contents: read
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: install deps
        run: pnpm install

      - name: Publish to npm
        run: pnpm release
